/*
* generated by Xtext
*/
package de.cau.cs.se.lad.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.cau.cs.se.lad.services.AppLangGrammarAccess;

public class AppLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AppLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.cau.cs.se.lad.parser.antlr.internal.InternalAppLangParser createParser(XtextTokenStream stream) {
		return new de.cau.cs.se.lad.parser.antlr.internal.InternalAppLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public AppLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AppLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
