/*
 * generated by Xtext
 */
package de.cau.cs.se.lad.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AppLangUiModule extends de.cau.cs.se.lad.ui.AbstractAppLangUiModule {
	public AppLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
