/*
* generated by Xtext
*/
package de.cau.cs.se.lad.ui.contentassist;

import de.cau.cs.se.lad.ui.contentassist.AbstractAppLangProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AppLangProposalProvider extends AbstractAppLangProposalProvider {

}
