/*
 * generated by Xtext
 */
package de.cau.cs.se.lad.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.cau.cs.se.lad.ui.internal.AppLangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AppLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AppLangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AppLangActivator.getInstance().getInjector(AppLangActivator.DE_CAU_CS_SE_LAD_APPLANG);
	}
	
}
