<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="appLang" nsURI="http://www.cau.de/cs/se/lad/AppLang" nsPrefix="appLang">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="ecore:EClass ../../../../../../model/Types.ecore#//ServiceType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//View" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="ecore:EClass ../../../../../../model/Types.ecore#//ClassType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//DataModel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//BaseExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//BaseExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringExpression" eSuperTypes="#//BaseExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="#//StringExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringProperty" eSuperTypes="#//StringValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="ecore:EClass ../../../../../../model/Types.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//StringValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullLiteral" eSuperTypes="#//BaseExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//FunctionEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FunctionEnum">
    <eLiterals name="DECODE" literal="decode"/>
    <eLiterals name="ENCODE" value="1" literal="encode"/>
    <eLiterals name="GET" value="2" literal="get"/>
    <eLiterals name="PUT" value="3" literal="put"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//Instance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" eType="#//Instance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../../../../../model/Types.ecore#//TypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//Layout"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//ViewContent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewContent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ViewContainer" eSuperTypes="#//ViewContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//Layout"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//ViewContent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewElement" eSuperTypes="#//ViewContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ViewType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ViewType">
    <eLiterals name="Button" literal="button"/>
    <eLiterals name="ValueSpinner" value="1" literal="value-spinner"/>
    <eLiterals name="DateSpinner" value="2" literal="date-spinner"/>
    <eLiterals name="Label" value="3" literal="label"/>
    <eLiterals name="TextOutput" value="4" literal="text"/>
    <eLiterals name="InputField" value="5" literal="input"/>
    <eLiterals name="Canvas" value="6" literal="canvas"/>
    <eLiterals name="TreeList" value="7" literal="tree-list"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//Size" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GridLayout" eSuperTypes="#//Layout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" eType="#//Field"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StackLayout" eSuperTypes="#//Layout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//Direction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Size">
    <eStructuralFeatures xsi:type="ecore:EReference" name="width" eType="#//SizeExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="height" eType="#//SizeExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SizeExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//Unit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Unit">
    <eLiterals name="PX" literal="px"/>
    <eLiterals name="PERCENT" value="1" literal="%"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="HORIZONTAL" literal="horizontal"/>
    <eLiterals name="VERTICAL" value="1" literal="vertical"/>
  </eClassifiers>
</ecore:EPackage>
