/*
* generated by Xtext
*/
package de.cau.cs.se.lad;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AppLangUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.cau.cs.se.lad.ui.internal.AppLangActivator.getInstance().getInjector("de.cau.cs.se.lad.AppLang");
	}
	
}
